trigger:
- master

pool:
  name: Default
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/jenkins/currency-exchange-microservice/Dockerfile'
        tags: |
          $(tag)
  - job: push
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerdevops'
        repository: '8985432404/test'
        command: 'push'
  
